spring.application.name=invoice-producer

# Configuracao do Servidor HTTP (Porta onde a API vai rodar)
server.port=8081

# Configuracoes de Conexao com o Kafka Local (WSL2)
spring.kafka.bootstrap-servers=localhost:9092

# Configuracao do Serializador (Transforma o objeto Java em JSON para enviar ao Kafka)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
