name: "Invoice Producer - [CD] Pipeline"

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Authenticate to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🚀 CD FASE 1: Compila em produção, gera a imagem e envia para o Docker Hub
      - name: Execute Docker Build and Push Shell Script
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }} # Tag única baseada no commit do Git
        run: |
          chmod +x ./scripts/cd-build.sh
          ./scripts/cd-build.sh
      # ☁️ CD FASE 2: Transfere o arquivo de deploy para a VM via SCP
      - name: Copy deployment script to OCI VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_CLOUD_IP }}
          username: opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "scripts/deploy-docker.sh"        # Caminho do arquivo no repositório GitHub
          target: "/home/opc/projetos/invoice-producer/scripts" # Pasta de destino na sua VM
          strip_components: 1                   # Evita que ele recrie a pasta 'scripts/' dentro do destino
      # ?? CD FASE 3: Conecta via SSH e apenas executa o script que já existe na VM
      - name: Execute OCI VM Remote Deployment
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.ORACLE_CLOUD_IP }}
          username: opc # Usuário padrão da VM Oracle Linux
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_TAG
          script_stop: true
          script: |
            # 1. Navega até a pasta onde o projeto está clonado na sua VM
            cd /home/opc/projetos/invoice-consumer
            
            # 2. Garante permissão e roda o script que veio no Git
            chmod +x ./scripts/deploy-docker.sh
            export IMAGE_TAG=$IMAGE_TAG
            ./scripts/deploy-docker.sh
      # ☸️ CD FASE 2: Atualiza o ambiente no Kubernetes
      #- name: Execute Kubernetes Remote Deployment Shell Script
      #  env:
      #    ORACLE_CLOUD_IP: ${{ secrets.ORACLE_CLOUD_IP }}
      #    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #    IMAGE_TAG: ${{ github.sha }}
      #  run: |
      #    chmod +x ./scripts/deploy-k8s.sh
      #    ./scripts/deploy-k8s.sh


